export const INIT = 'INIT'
export const STARTWORK = 'STARTWORK'
export const STOPWORK = 'STOPWORK'
export const COMPUTED = 'COMPUTED'
export const SHOWMODAL = 'SHOWTMODAL'
export const HIDEMODAL = 'HIDETMODAL'